sudo: required
services:
 - docker


before_install:
 - docker build -t basemabdulrahem/docker-react -f Dockerfile.dev .


script:
 - docker run -e CI=true basemabdulrahem/docker-react npm run test -- --coverage

